"""
JARVIS Backend Agent — SE Layer.

Generates production-ready backend code based on an ArchitectureSpec:
  - FastAPI apps with full CRUD, JWT auth, SQLAlchemy ORM
  - Flask blueprints with extensions
  - Django REST Framework views and serializers
  - Spring Boot controller/service/repository stubs

All generated files are written to workspace/{project}/backend/
"""

from __future__ import annotations

import os
from typing import Any

from JARVIS.core.system.utils.jarvis_logging import get_logger
from JARVIS.core.software_engineering.agents.architect_agent import ArchitectureSpec

logger = get_logger("backend_agent")


class BackendAgent:
    """Generates backend source code from an ArchitectureSpec."""

    def generate(self, spec: ArchitectureSpec) -> dict[str, Any]:
        """Generate all backend files and return a result manifest."""
        if not spec.backend_stack:
            return {"success": True, "files": [], "message": "No backend stack required."}

        logger.info("BackendAgent generating %s backend for %s", spec.backend_stack, spec.project_name)

        backend_dir = os.path.join(spec.workspace_path, "backend")
        files_written: list[str] = []

        stack = spec.backend_stack.lower()

        if "fastapi" in stack:
            files_written += self._generate_fastapi(spec, backend_dir)
        elif "flask" in stack:
            files_written += self._generate_flask(spec, backend_dir)
        elif "django" in stack:
            files_written += self._generate_django(spec, backend_dir)
        elif "spring" in stack:
            files_written += self._generate_spring(spec, backend_dir)
        else:
            files_written += self._generate_fastapi(spec, backend_dir)  # default

        return {
            "success": True,
            "files": files_written,
            "backend_stack": spec.backend_stack,
            "message": f"Generated {len(files_written)} backend files using {spec.backend_stack}.",
        }

    # ── FastAPI Generation ────────────────────────────────────────────────────

    def _generate_fastapi(self, spec: ArchitectureSpec, out_dir: str) -> list[str]:
        written: list[str] = []
        app_dir = os.path.join(out_dir, "app")
        has_auth = "auth" in spec.features

        # main.py
        written.append(self._write(out_dir, "main.py", self._fastapi_main(spec)))

        # app/core/config.py
        written.append(self._write(os.path.join(app_dir, "core"), "config.py", self._fastapi_config(spec)))

        # app/core/security.py
        if has_auth:
            written.append(self._write(os.path.join(app_dir, "core"), "security.py", self._fastapi_security()))

        # app/models/models.py
        written.append(self._write(os.path.join(app_dir, "models"), "models.py", self._fastapi_models(spec)))

        # app/schemas/schemas.py
        written.append(self._write(os.path.join(app_dir, "schemas"), "schemas.py", self._fastapi_schemas(spec)))

        # app/services/item_service.py
        written.append(self._write(os.path.join(app_dir, "services"), "item_service.py", self._fastapi_service(spec)))

        # app/routes/items.py
        written.append(self._write(os.path.join(app_dir, "routes"), "items.py", self._fastapi_items_router(spec)))

        # app/routes/auth.py
        if has_auth:
            written.append(self._write(os.path.join(app_dir, "routes"), "auth.py", self._fastapi_auth_router()))

        # app/database.py
        written.append(self._write(app_dir, "database.py", self._fastapi_database(spec)))

        # requirements.txt
        written.append(self._write(out_dir, "requirements.txt", "\n".join(spec.backend_deps)))

        # .env.example
        written.append(self._write(out_dir, ".env.example", self._env_example(spec)))

        # README.md
        written.append(self._write(out_dir, "README.md", self._backend_readme(spec)))

        return written

    def _fastapi_main(self, spec: ArchitectureSpec) -> str:
        has_auth = "auth" in spec.features
        auth_import = "from app.routes import auth" if has_auth else ""
        auth_include = '    app.include_router(auth.router, prefix="/api/auth", tags=["auth"])' if has_auth else ""
        return f'''"""
{spec.project_name} — FastAPI Application Entry Point
Generated by JARVIS Autonomous Software Engineering Platform
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.database import Base, engine
from app.routes import items
{auth_import}

Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="{spec.project_name.replace("_", " ").title()} API",
    description="Auto-generated by JARVIS SE Platform",
    version="1.0.0",
    docs_url="/api/docs",
    redoc_url="/api/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(items.router, prefix="/api/items", tags=["items"])
{auth_include}


@app.get("/api/health")
async def health_check():
    return {{"status": "online", "service": "{spec.project_name}"}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
'''

    def _fastapi_config(self, spec: ArchitectureSpec) -> str:
        return f'''"""Application Configuration"""
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    APP_NAME: str = "{spec.project_name.title()}"
    DATABASE_URL: str = "sqlite:///./{spec.project_name}.db"
    SECRET_KEY: str = "change-me-in-production-use-secrets"
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30

    class Config:
        env_file = ".env"


settings = Settings()
'''

    def _fastapi_security(self) -> str:
        return '''"""JWT Security utilities"""
from datetime import datetime, timedelta
from typing import Optional
from jose import JWTError, jwt
from passlib.context import CryptContext
from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from app.core.config import settings

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/auth/login")


def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)


def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)


def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES))
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)


def decode_token(token: str) -> dict:
    try:
        return jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
    except JWTError:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")
'''

    def _fastapi_models(self, spec: ArchitectureSpec) -> str:
        has_auth = "auth" in spec.features
        user_model = '''
class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, index=True, nullable=False)
    email = Column(String(120), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    items = relationship("Item", back_populates="owner")
''' if has_auth else ""

        owner_field = "    owner_id = Column(Integer, ForeignKey('users.id'), nullable=True)" if has_auth else ""
        owner_rel = "    owner = relationship('User', back_populates='items')" if has_auth else ""

        return f'''"""SQLAlchemy Database Models"""
from datetime import datetime
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from app.database import Base
{user_model}

class Item(Base):
    __tablename__ = "items"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)
    is_completed = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
{owner_field}
{owner_rel}
'''

    def _fastapi_schemas(self, spec: ArchitectureSpec) -> str:
        has_auth = "auth" in spec.features
        user_schemas = '''
class UserBase(BaseModel):
    username: str
    email: str

class UserCreate(UserBase):
    password: str

class UserResponse(UserBase):
    id: int
    is_active: bool
    created_at: datetime
    class Config:
        from_attributes = True

class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"

class TokenData(BaseModel):
    username: Optional[str] = None
''' if has_auth else ""

        return f'''"""Pydantic Schemas"""
from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel
{user_schemas}

class ItemBase(BaseModel):
    title: str
    description: Optional[str] = None
    is_completed: bool = False

class ItemCreate(ItemBase):
    pass

class ItemUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    is_completed: Optional[bool] = None

class ItemResponse(ItemBase):
    id: int
    created_at: datetime
    updated_at: datetime
    class Config:
        from_attributes = True

class PaginatedItems(BaseModel):
    items: List[ItemResponse]
    total: int
    page: int
    per_page: int
'''

    def _fastapi_service(self, spec: ArchitectureSpec) -> str:
        return '''"""Item Business Logic Service"""
from typing import List, Optional
from sqlalchemy.orm import Session
from app.models.models import Item
from app.schemas.schemas import ItemCreate, ItemUpdate


def get_items(db: Session, skip: int = 0, limit: int = 100) -> List[Item]:
    return db.query(Item).offset(skip).limit(limit).all()


def get_item(db: Session, item_id: int) -> Optional[Item]:
    return db.query(Item).filter(Item.id == item_id).first()


def create_item(db: Session, item: ItemCreate) -> Item:
    db_item = Item(**item.model_dump())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item


def update_item(db: Session, item_id: int, item: ItemUpdate) -> Optional[Item]:
    db_item = get_item(db, item_id)
    if not db_item:
        return None
    for field, value in item.model_dump(exclude_unset=True).items():
        setattr(db_item, field, value)
    db.commit()
    db.refresh(db_item)
    return db_item


def delete_item(db: Session, item_id: int) -> bool:
    db_item = get_item(db, item_id)
    if not db_item:
        return False
    db.delete(db_item)
    db.commit()
    return True
'''

    def _fastapi_items_router(self, spec: ArchitectureSpec) -> str:
        return '''"""Items REST API Router"""
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.orm import Session
from app.database import get_db
from app.schemas.schemas import ItemCreate, ItemUpdate, ItemResponse
from app.services import item_service

router = APIRouter()


@router.get("/", response_model=List[ItemResponse])
async def list_items(
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=500),
    db: Session = Depends(get_db),
):
    return item_service.get_items(db, skip=skip, limit=limit)


@router.post("/", response_model=ItemResponse, status_code=status.HTTP_201_CREATED)
async def create_item(item: ItemCreate, db: Session = Depends(get_db)):
    return item_service.create_item(db, item)


@router.get("/{item_id}", response_model=ItemResponse)
async def get_item(item_id: int, db: Session = Depends(get_db)):
    item = item_service.get_item(db, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item


@router.put("/{item_id}", response_model=ItemResponse)
async def update_item(item_id: int, item: ItemUpdate, db: Session = Depends(get_db)):
    updated = item_service.update_item(db, item_id, item)
    if not updated:
        raise HTTPException(status_code=404, detail="Item not found")
    return updated


@router.delete("/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_item(item_id: int, db: Session = Depends(get_db)):
    if not item_service.delete_item(db, item_id):
        raise HTTPException(status_code=404, detail="Item not found")
'''

    def _fastapi_auth_router(self) -> str:
        return '''"""Authentication Router"""
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.models import User
from app.schemas.schemas import UserCreate, UserResponse, Token
from app.core.security import get_password_hash, verify_password, create_access_token

router = APIRouter()


@router.post("/register", response_model=UserResponse, status_code=201)
async def register(user: UserCreate, db: Session = Depends(get_db)):
    if db.query(User).filter(User.email == user.email).first():
        raise HTTPException(status_code=400, detail="Email already registered")
    db_user = User(
        username=user.username,
        email=user.email,
        hashed_password=get_password_hash(user.password),
    )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user


@router.post("/login", response_model=Token)
async def login(form: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    user = db.query(User).filter(User.username == form.username).first()
    if not user or not verify_password(form.password, user.hashed_password):
        raise HTTPException(status_code=401, detail="Incorrect credentials")
    token = create_access_token({"sub": user.username})
    return {"access_token": token, "token_type": "bearer"}


@router.get("/me", response_model=UserResponse)
async def get_me(db: Session = Depends(get_db)):
    # Placeholder — inject current_user via OAuth2 dependency in production
    raise HTTPException(status_code=501, detail="Implement get_current_user dependency")
'''

    def _fastapi_database(self, spec: ArchitectureSpec) -> str:
        return f'''"""Database Connection & Session"""
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker
from app.core.config import settings

engine = create_engine(
    settings.DATABASE_URL,
    connect_args={{"check_same_thread": False}} if "sqlite" in settings.DATABASE_URL else {{}},
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''

    # ── Flask ─────────────────────────────────────────────────────────────────

    def _generate_flask(self, spec: ArchitectureSpec, out_dir: str) -> list[str]:
        written = []
        written.append(self._write(out_dir, "app.py", f'''"""Flask Application — {spec.project_name}
Generated by JARVIS SE Platform
"""
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_cors import CORS

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///{spec.project_name}.db"
app.config["SECRET_KEY"] = "change-me-in-production"
CORS(app)

db = SQLAlchemy(app)

from routes import items_bp
app.register_blueprint(items_bp, url_prefix="/api/items")

if __name__ == "__main__":
    with app.app_context():
        db.create_all()
    app.run(debug=True, host="0.0.0.0", port=5000)
'''))
        written.append(self._write(out_dir, "requirements.txt", "\n".join(spec.backend_deps)))
        written.append(self._write(out_dir, ".env.example", self._env_example(spec)))
        return written

    # ── Django ────────────────────────────────────────────────────────────────

    def _generate_django(self, spec: ArchitectureSpec, out_dir: str) -> list[str]:
        written = []
        written.append(self._write(out_dir, "manage.py", f'''#!/usr/bin/env python
"""Django manage.py — {spec.project_name}"""
import os, sys

def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)

if __name__ == "__main__":
    main()
'''))
        written.append(self._write(out_dir, "requirements.txt", "\n".join(spec.backend_deps)))
        return written

    # ── Spring Boot ───────────────────────────────────────────────────────────

    def _generate_spring(self, spec: ArchitectureSpec, out_dir: str) -> list[str]:
        name = spec.project_name.replace("_", "").title()
        written = []
        written.append(self._write(out_dir, f"{name}Application.java", f'''package com.{spec.project_name};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class {name}Application {{
    public static void main(String[] args) {{
        SpringApplication.run({name}Application.class, args);
    }}
}}
'''))
        written.append(self._write(out_dir, "pom.xml", f'''<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.{spec.project_name}</groupId>
    <artifactId>{spec.project_name}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
    </parent>
    <dependencies>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency>
        <dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId><scope>runtime</scope></dependency>
    </dependencies>
</project>
'''))
        return written

    # ── Shared helpers ────────────────────────────────────────────────────────

    def _env_example(self, spec: ArchitectureSpec) -> str:
        return f"""# {spec.project_name} Environment Variables
DATABASE_URL=sqlite:///{spec.project_name}.db
SECRET_KEY=your-secret-key-here
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
DEBUG=True
"""

    def _backend_readme(self, spec: ArchitectureSpec) -> str:
        return f"""# {spec.project_name.replace("_", " ").title()} — Backend

**Stack:** {spec.backend_stack} | **Database:** {spec.database} | **Auth:** {spec.auth_method}

## Quick Start

```bash
cd backend
python -m venv .venv && source .venv/bin/activate  # Windows: .venv\\Scripts\\activate
pip install -r requirements.txt
cp .env.example .env
python main.py
```

API docs available at: http://localhost:8000/api/docs

## Generated by JARVIS Autonomous SE Platform
"""

    def _write(self, directory: str, filename: str, content: str) -> str:
        os.makedirs(directory, exist_ok=True)
        path = os.path.join(directory, filename)
        try:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            logger.debug("BackendAgent wrote: %s", path)
            return path
        except Exception as e:
            logger.error("BackendAgent write error for %s: %s", path, e)
            return path
