"""
JARVIS Documentation Agent — SE Layer.

Generates complete project documentation:
  - README.md with full project description, setup, and usage
  - API_DOCS.md with all endpoint documentation
  - ARCHITECTURE.md with Mermaid system diagram
  - DEPLOYMENT.md with Docker + cloud deployment guide
  - CHANGELOG.md structured changelog
"""

from __future__ import annotations

import os
from typing import Any

from JARVIS.core.software_engineering.agents.architect_agent import ArchitectureSpec
from JARVIS.core.system.utils.jarvis_logging import get_logger

logger = get_logger("documentation_agent")


class DocumentationAgent:
    """Generates complete project documentation from an ArchitectureSpec."""

    def generate(self, spec: ArchitectureSpec) -> dict[str, Any]:
        logger.info("DocumentationAgent generating docs for %s", spec.project_name)
        docs_dir = os.path.join(spec.workspace_path, "docs")
        files_written: list[str] = []

        files_written.append(self._write(spec.workspace_path, "README.md", self._readme(spec)))
        files_written.append(self._write(docs_dir, "API_DOCS.md", self._api_docs(spec)))
        files_written.append(self._write(docs_dir, "ARCHITECTURE.md", self._architecture(spec)))
        files_written.append(self._write(docs_dir, "DEPLOYMENT.md", self._deployment(spec)))
        files_written.append(self._write(docs_dir, "CHANGELOG.md", self._changelog(spec)))

        return {
            "success": True,
            "files": files_written,
            "message": f"Generated {len(files_written)} documentation files.",
        }

    def generate_for_error_fix(self, error: str, fix: str, project_name: str, workspace: str) -> dict[str, Any]:
        """Generate a debugging report document."""
        docs_dir = os.path.join(workspace, "docs")
        content = f"""# Debugging Report — {project_name}

## Error Encountered

```
{error[:2000]}
```

## Root Cause & Fix Applied

{fix}

---
*Generated by JARVIS Debugger Agent*
"""
        path = self._write(docs_dir, "DEBUG_REPORT.md", content)
        return {"success": True, "files": [path], "message": "Debug report generated."}

    # ── README ────────────────────────────────────────────────────────────────

    def _readme(self, spec: ArchitectureSpec) -> str:
        title = spec.project_name.replace("_", " ").title()

        stacks: list[str] = []
        if spec.backend_stack:
            stacks.append(f"**Backend:** {spec.backend_stack}")
        if spec.frontend_stack:
            stacks.append(f"**Frontend:** {spec.frontend_stack}")
        if spec.mobile_stack:
            stacks.append(f"**Mobile:** {spec.mobile_stack}")
        if spec.ml_stack:
            stacks.append(f"**ML:** {spec.ml_stack}")

        quick_start_backend = ""
        if spec.backend_stack and "fastapi" in spec.backend_stack.lower():
            quick_start_backend = """
### Backend Setup

```bash
cd backend
python -m venv .venv
# Windows: .venv\\Scripts\\activate  |  Linux/Mac: source .venv/bin/activate
pip install -r requirements.txt
cp .env.example .env
python main.py
```

Backend API: http://localhost:8000
Interactive docs: http://localhost:8000/api/docs
"""
        elif spec.backend_stack and "flask" in spec.backend_stack.lower():
            quick_start_backend = """
### Backend Setup

```bash
cd backend
pip install -r requirements.txt
cp .env.example .env
python app.py
```
"""
        quick_start_frontend = ""
        if spec.frontend_stack:
            quick_start_frontend = """
### Frontend Setup

```bash
cd frontend
npm install
cp .env.example .env
npm run dev
```

Frontend: http://localhost:5173
"""
        quick_start_mobile = ""
        if spec.mobile_stack == "Flutter":
            quick_start_mobile = """
### Mobile Setup (Flutter)

```bash
cd mobile
flutter pub get
flutter run
# Build release APK:
flutter build apk --release
```
"""

        features_list = "\n".join(f"- {f.replace('-', ' ').title()}" for f in spec.features)
        endpoints_table = self._endpoints_table(spec.api_endpoints) if spec.api_endpoints else ""

        return f"""# {title}

> {spec.description}

**Generated autonomously by [JARVIS SE Platform](https://github.com/JARVIS)**

---

## Tech Stack

{chr(10).join(f"- {s}" for s in stacks)}
- **Database:** {spec.database}
- **Authentication:** {spec.auth_method}

## Features

{features_list}

## Quick Start
{quick_start_backend}
{quick_start_frontend}
{quick_start_mobile}
## API Endpoints

{endpoints_table}

## Project Structure

```
{spec.project_name}/
├── backend/            # {spec.backend_stack or "N/A"} API
├── frontend/           # {spec.frontend_stack or "N/A"} UI
├── mobile/             # {spec.mobile_stack or "N/A"} App
├── tests/              # Test suites
├── devops/             # Docker + CI/CD
└── docs/               # Documentation
```

## Documentation

- [API Documentation](docs/API_DOCS.md)
- [Architecture](docs/ARCHITECTURE.md)
- [Deployment Guide](docs/DEPLOYMENT.md)
- [Changelog](docs/CHANGELOG.md)

---

*Built with JARVIS Autonomous Software Engineering Platform | v1.0.0*
"""

    def _endpoints_table(self, endpoints: list[dict]) -> str:
        if not endpoints:
            return "_No endpoints defined._"
        rows = ["| Method | Path | Description | Auth Required |", "|--------|------|-------------|---------------|"]
        for ep in endpoints:
            auth = "✅" if ep.get("auth") else "❌"
            rows.append(f"| `{ep['method']}` | `{ep['path']}` | {ep['description']} | {auth} |")
        return "\n".join(rows)

    # ── API DOCS ──────────────────────────────────────────────────────────────

    def _api_docs(self, spec: ArchitectureSpec) -> str:
        title = spec.project_name.replace("_", " ").title()
        endpoint_docs = "\n\n".join(self._endpoint_doc(ep) for ep in spec.api_endpoints)

        return f"""# {title} — API Documentation

**Base URL:** `http://localhost:8000`  
**Interactive Docs:** `http://localhost:8000/api/docs`  
**Version:** 1.0.0  
**Authentication:** {spec.auth_method}

---

## Authentication

{"### JWT Bearer Token" if spec.auth_method == "JWT" else "No authentication required."}

{"All protected endpoints require the `Authorization: Bearer <token>` header." if spec.auth_method == "JWT" else ""}

{"```bash" if spec.auth_method == "JWT" else ""}
{"# Get token:" if spec.auth_method == "JWT" else ""}
{"curl -X POST http://localhost:8000/api/auth/login \\\\" if spec.auth_method == "JWT" else ""}
{"  -d 'username=admin&password=secret'" if spec.auth_method == "JWT" else ""}
{"```" if spec.auth_method == "JWT" else ""}

---

## Endpoints

{endpoint_docs}

---

## Error Responses

| Status | Meaning |
|--------|---------|
| 200 | Success |
| 201 | Created |
| 204 | Deleted (no content) |
| 400 | Bad Request |
| 401 | Unauthorized |
| 404 | Not Found |
| 422 | Validation Error |
| 500 | Internal Server Error |

---

*Generated by JARVIS Documentation Agent*
"""

    def _endpoint_doc(self, ep: dict) -> str:
        auth_note = "\n> 🔒 **Authentication required.** Include `Authorization: Bearer <token>` header." if ep.get("auth") else ""
        method = ep["method"]
        path = ep["path"]
        desc = ep["description"]

        example = ""
        if method in ("POST", "PUT") and "item" in path.lower():
            example = """
**Request Body:**
```json
{
  "title": "My Item",
  "description": "Optional description",
  "is_completed": false
}
```
**Response (201):**
```json
{
  "id": 1,
  "title": "My Item",
  "description": "Optional description",
  "is_completed": false,
  "created_at": "2026-07-01T10:00:00",
  "updated_at": "2026-07-01T10:00:00"
}
```"""
        elif method == "GET" and "{id}" not in path:
            example = """
**Response (200):**
```json
[
  {"id": 1, "title": "Item 1", "is_completed": false, ...},
  {"id": 2, "title": "Item 2", "is_completed": true, ...}
]
```"""

        return f"""### `{method} {path}`

{desc}{auth_note}
{example}
"""

    # ── ARCHITECTURE ──────────────────────────────────────────────────────────

    def _architecture(self, spec: ArchitectureSpec) -> str:
        title = spec.project_name.replace("_", " ").title()

        # Build Mermaid diagram
        mermaid_nodes: list[str] = ['    Client["Browser / Mobile App"]']
        mermaid_edges: list[str] = []

        if spec.frontend_stack:
            mermaid_nodes.append(f'    Frontend["{spec.frontend_stack}\\nPort 5173"]')
            mermaid_edges.append("    Client --> Frontend")

        if spec.backend_stack:
            mermaid_nodes.append(f'    Backend["{spec.backend_stack} API\\nPort 8000"]')
            mermaid_edges.append("    Client --> Backend")
            if spec.frontend_stack:
                mermaid_edges.append("    Frontend --> Backend")

        if spec.database:
            mermaid_nodes.append(f'    DB[("{spec.database}")]')
            mermaid_edges.append("    Backend --> DB")

        mermaid_lines = "\n".join(mermaid_nodes + mermaid_edges)

        data_models_section = ""
        for model in spec.data_models:
            fields = "\n".join(f"    + {f['type']} {f['name']}" for f in model["fields"])
            data_models_section += f"\n### {model['name']}\n\n```\n{model['name']}\n{fields}\n```\n"

        return f"""# {title} — Architecture

## System Overview

```mermaid
graph TB
{mermaid_lines}
```

## Technology Decisions

| Component | Technology | Rationale |
|-----------|-----------|-----------|
| Backend | {spec.backend_stack or "N/A"} | {self._backend_rationale(spec.backend_stack)} |
| Frontend | {spec.frontend_stack or "N/A"} | {self._frontend_rationale(spec.frontend_stack)} |
| Database | {spec.database} | {self._db_rationale(spec.database)} |
| Auth | {spec.auth_method} | {self._auth_rationale(spec.auth_method)} |

## Data Models
{data_models_section if data_models_section else "_No data models defined._"}

## API Endpoints

{self._endpoints_table(spec.api_endpoints)}

---

*Generated by JARVIS Architecture Documentation Agent*
"""

    def _backend_rationale(self, stack: str | None) -> str:
        return {
            "FastAPI": "High performance async, auto OpenAPI docs, Pydantic validation",
            "Flask": "Lightweight, flexible, battle-tested Python web framework",
            "Django": "Batteries included, strong ORM, admin panel, large ecosystem",
            "Spring Boot": "Enterprise-grade Java framework with strong typing and DI",
        }.get(stack or "", "Matches project requirements")

    def _frontend_rationale(self, stack: str | None) -> str:
        return {
            "React": "Component-based, large ecosystem, hooks pattern",
            "Next.js": "SSR/SSG support, TypeScript, Vercel deployment ready",
            "Vanilla HTML/CSS/JS": "Zero dependencies, fastest load time",
        }.get(stack or "", "Matches project requirements")

    def _db_rationale(self, db: str) -> str:
        return {
            "SQLite": "Zero-config, file-based, perfect for development",
            "PostgreSQL": "Production-grade, ACID compliant, advanced indexing",
            "MySQL": "High performance, wide hosting support",
            "MongoDB": "Flexible document store for unstructured data",
        }.get(db, "Matches project requirements")

    def _auth_rationale(self, auth: str) -> str:
        return {
            "JWT": "Stateless, scalable, industry standard for REST APIs",
            "Session": "Traditional server-side sessions for web applications",
            "None": "No authentication required for this service",
        }.get(auth, "Matches project requirements")

    # ── DEPLOYMENT ────────────────────────────────────────────────────────────

    def _deployment(self, spec: ArchitectureSpec) -> str:
        title = spec.project_name.replace("_", " ").title()
        return f"""# {title} — Deployment Guide

## Local Development

```bash
# Backend
cd backend && python main.py

# Frontend (separate terminal)
cd frontend && npm run dev
```

## Docker Deployment

```bash
# Build and start all services
docker-compose up --build -d

# View logs
docker-compose logs -f

# Stop
docker-compose down
```

See [devops/docker-compose.yml](../devops/docker-compose.yml) for configuration.

## Production Checklist

- [ ] Change `SECRET_KEY` in `.env` to a strong random value
- [ ] Set `DEBUG=False`
- [ ] Use PostgreSQL instead of SQLite
- [ ] Enable HTTPS with SSL certificate
- [ ] Set up database backups
- [ ] Configure rate limiting
- [ ] Set up monitoring (Sentry, Datadog, etc.)
- [ ] Configure CORS for production domain

## CI/CD (GitHub Actions)

Push to `main` branch triggers automatic:
1. Run test suite
2. Build Docker image
3. Push to container registry
4. Deploy to staging

See [.github/workflows/ci.yml](../.github/workflows/ci.yml)

---

*Generated by JARVIS Documentation Agent*
"""

    # ── CHANGELOG ────────────────────────────────────────────────────────────

    def _changelog(self, spec: ArchitectureSpec) -> str:
        import time

        date = time.strftime("%Y-%m-%d")
        return f"""# Changelog

All notable changes to {spec.project_name.replace("_", " ").title()} are documented here.

Format follows [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

---

## [1.0.0] — {date}

### Added
- Initial project scaffold generated by JARVIS SE Platform
- {spec.backend_stack or "N/A"} backend with REST API
- {spec.frontend_stack or "N/A"} frontend
- {spec.database} database integration
- {spec.auth_method} authentication
- Complete test suite (pytest + {"Vitest" if spec.frontend_stack else "N/A"})
- Docker containerisation
- GitHub Actions CI/CD pipeline
- Full API documentation (OpenAPI/Swagger)

### Stack
- Backend: {spec.backend_stack}
- Frontend: {spec.frontend_stack}
- Database: {spec.database}
- Auth: {spec.auth_method}

---

*JARVIS SE Platform — Autonomous Software Engineering*
"""

    def _write(self, directory: str, filename: str, content: str) -> str:
        os.makedirs(directory, exist_ok=True)
        path = os.path.join(directory, filename)
        try:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            return path
        except Exception as e:
            logger.error("DocumentationAgent write error: %s", e)
            return path
