"""
JARVIS Mobile Agent — SE Layer.

Generates Flutter and Android Native project scaffolds:
  - Full Flutter Dart project structure with Riverpod state management
  - pubspec.yaml with all dependencies
  - Material 3 screens with navigation
  - API service layer using Dio
  - Proposes (but does NOT auto-run) flutter CLI commands
"""

from __future__ import annotations

import os
from typing import Any

from JARVIS.core.software_engineering.agents.architect_agent import ArchitectureSpec
from JARVIS.core.system.utils.jarvis_logging import get_logger

logger = get_logger("mobile_agent")


class MobileAgent:
    """Generates Flutter/Android project code from an ArchitectureSpec."""

    def generate(self, spec: ArchitectureSpec) -> dict[str, Any]:
        if not spec.mobile_stack:
            return {"success": True, "files": [], "message": "No mobile stack required."}

        logger.info("MobileAgent generating %s project for %s", spec.mobile_stack, spec.project_name)
        mobile_dir = os.path.join(spec.workspace_path, "mobile")
        files_written: list[str] = []

        if spec.mobile_stack == "Flutter":
            files_written += self._generate_flutter(spec, mobile_dir)
        elif spec.mobile_stack == "Android Native":
            files_written += self._generate_android(spec, mobile_dir)

        # Proposed (not executed) CLI commands
        proposed_commands = self._get_proposed_commands(spec, mobile_dir)

        return {
            "success": True,
            "files": files_written,
            "mobile_stack": spec.mobile_stack,
            "proposed_commands": proposed_commands,
            "message": (
                f"Generated {len(files_written)} {spec.mobile_stack} files. "
                f"Run the following commands to build (requires user approval): "
                f"{'; '.join(proposed_commands)}"
            ),
        }

    # ── Flutter Generation ────────────────────────────────────────────────────

    def _generate_flutter(self, spec: ArchitectureSpec, out_dir: str) -> list[str]:
        written: list[str] = []
        lib_dir = os.path.join(out_dir, "lib")
        title = spec.project_name.replace("_", " ").title()
        has_auth = "auth" in spec.features

        written.append(self._write(out_dir, "pubspec.yaml", self._pubspec(spec)))
        written.append(self._write(out_dir, ".gitignore", self._flutter_gitignore()))
        written.append(self._write(out_dir, "README.md", self._mobile_readme(spec)))

        # lib/main.dart
        written.append(self._write(lib_dir, "main.dart", self._flutter_main(spec)))

        # lib/app.dart
        written.append(self._write(lib_dir, "app.dart", self._flutter_app(spec, has_auth)))

        # lib/models/item.dart
        written.append(self._write(os.path.join(lib_dir, "models"), "item.dart", self._flutter_item_model()))

        # lib/services/api_service.dart
        written.append(self._write(os.path.join(lib_dir, "services"), "api_service.dart", self._flutter_api_service(spec)))

        # lib/providers/items_provider.dart
        written.append(self._write(os.path.join(lib_dir, "providers"), "items_provider.dart", self._flutter_items_provider()))

        # lib/screens/home_screen.dart
        written.append(self._write(os.path.join(lib_dir, "screens"), "home_screen.dart", self._flutter_home_screen(title)))

        # lib/screens/items_screen.dart
        written.append(self._write(os.path.join(lib_dir, "screens"), "items_screen.dart", self._flutter_items_screen()))

        # lib/widgets/item_tile.dart
        written.append(self._write(os.path.join(lib_dir, "widgets"), "item_tile.dart", self._flutter_item_tile()))

        if has_auth:
            written.append(self._write(os.path.join(lib_dir, "screens"), "login_screen.dart", self._flutter_login_screen()))

        return written

    def _pubspec(self, spec: ArchitectureSpec) -> str:
        return f"""name: {spec.project_name}
description: {spec.project_name.replace("_", " ").title()} — Generated by JARVIS SE Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  dio: ^5.4.0
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
"""

    def _flutter_main(self, spec: ArchitectureSpec) -> str:
        return f"""import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app.dart';

void main() {{
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const ProviderScope(child: {spec.project_name.replace("_", "").title()}App()));
}}
"""

    def _flutter_app(self, spec: ArchitectureSpec, has_auth: bool) -> str:
        name = spec.project_name.replace("_", "").title()
        title = spec.project_name.replace("_", " ").title()
        login_route = (
            """
    GoRoute(path: '/login', builder: (context, state) => const LoginScreen()),"""
            if has_auth
            else ""
        )

        return f"""import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'screens/home_screen.dart';
import 'screens/items_screen.dart';
{"import 'screens/login_screen.dart';" if has_auth else ""}

class {name}App extends StatelessWidget {{
  const {name}App({{super.key}});

  @override
  Widget build(BuildContext context) {{
    final router = GoRouter(
      initialLocation: '/',
      routes: [
        GoRoute(path: '/', builder: (context, state) => const HomeScreen()),
        GoRoute(path: '/items', builder: (context, state) => const ItemsScreen()),{login_route}
      ],
    );

    return MaterialApp.router(
      title: '{title}',
      routerConfig: router,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF2563EB)),
        useMaterial3: true,
      ),
      debugShowCheckedModeBanner: false,
    );
  }}
}}
"""

    def _flutter_item_model(self) -> str:
        return """class Item {
  final int id;
  final String title;
  final String? description;
  final bool isCompleted;
  final DateTime createdAt;

  const Item({
    required this.id,
    required this.title,
    this.description,
    required this.isCompleted,
    required this.createdAt,
  });

  factory Item.fromJson(Map<String, dynamic> json) => Item(
        id: json['id'] as int,
        title: json['title'] as String,
        description: json['description'] as String?,
        isCompleted: json['is_completed'] as bool,
        createdAt: DateTime.parse(json['created_at'] as String),
      );

  Map<String, dynamic> toJson() => {
        'title': title,
        'description': description,
        'is_completed': isCompleted,
      };

  Item copyWith({String? title, String? description, bool? isCompleted}) => Item(
        id: id,
        title: title ?? this.title,
        description: description ?? this.description,
        isCompleted: isCompleted ?? this.isCompleted,
        createdAt: createdAt,
      );
}
"""

    def _flutter_api_service(self, spec: ArchitectureSpec) -> str:
        return """import 'package:dio/dio.dart';
import '../models/item.dart';

class ApiService {
  static const String _baseUrl = 'http://10.0.2.2:8000'; // Android emulator
  late final Dio _dio;

  ApiService() {
    _dio = Dio(BaseOptions(
      baseUrl: _baseUrl,
      connectTimeout: const Duration(seconds: 10),
      receiveTimeout: const Duration(seconds: 10),
    ));
    _dio.interceptors.add(LogInterceptor(responseBody: true));
  }

  Future<List<Item>> getItems() async {
    final response = await _dio.get('/api/items/');
    return (response.data as List).map((j) => Item.fromJson(j)).toList();
  }

  Future<Item> createItem({required String title, String? description}) async {
    final response = await _dio.post('/api/items/', data: {
      'title': title,
      'description': description,
    });
    return Item.fromJson(response.data);
  }

  Future<Item> updateItem(int id, {bool? isCompleted, String? title}) async {
    final response = await _dio.put('/api/items/$id', data: {
      if (title != null) 'title': title,
      if (isCompleted != null) 'is_completed': isCompleted,
    });
    return Item.fromJson(response.data);
  }

  Future<void> deleteItem(int id) async {
    await _dio.delete('/api/items/$id');
  }
}
"""

    def _flutter_items_provider(self) -> str:
        return """import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/item.dart';
import '../services/api_service.dart';

final apiServiceProvider = Provider<ApiService>((ref) => ApiService());

final itemsProvider = AsyncNotifierProvider<ItemsNotifier, List<Item>>(ItemsNotifier.new);

class ItemsNotifier extends AsyncNotifier<List<Item>> {
  @override
  Future<List<Item>> build() => ref.read(apiServiceProvider).getItems();

  Future<void> addItem(String title, {String? description}) async {
    final item = await ref.read(apiServiceProvider).createItem(title: title, description: description);
    state = AsyncData([item, ...state.valueOrNull ?? []]);
  }

  Future<void> toggleItem(Item item) async {
    final updated = await ref.read(apiServiceProvider).updateItem(item.id, isCompleted: !item.isCompleted);
    state = AsyncData(state.valueOrNull?.map((i) => i.id == item.id ? updated : i).toList() ?? []);
  }

  Future<void> deleteItem(int id) async {
    await ref.read(apiServiceProvider).deleteItem(id);
    state = AsyncData(state.valueOrNull?.where((i) => i.id != id).toList() ?? []);
  }
}
"""

    def _flutter_home_screen(self, title: str) -> str:
        return f"""import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class HomeScreen extends StatelessWidget {{
  const HomeScreen({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.auto_awesome, size: 80, color: Color(0xFF2563EB)),
              const SizedBox(height: 24),
              Text('{title}',
                style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              const Text('Built with JARVIS SE Platform', style: TextStyle(color: Colors.grey)),
              const SizedBox(height: 48),
              FilledButton.icon(
                onPressed: () => context.go('/items'),
                icon: const Icon(Icons.list),
                label: const Text('View Items'),
                style: FilledButton.styleFrom(
                  minimumSize: const Size(200, 52),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }}
}}
"""

    def _flutter_items_screen(self) -> str:
        return """import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/items_provider.dart';
import '../widgets/item_tile.dart';

class ItemsScreen extends ConsumerWidget {
  const ItemsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final items = ref.watch(itemsProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('Items'), centerTitle: true,
        backgroundColor: const Color(0xFF2563EB), foregroundColor: Colors.white),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showAddDialog(context, ref),
        child: const Icon(Icons.add),
      ),
      body: items.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, _) => Center(child: Text('Error: $e')),
        data: (itemList) => itemList.isEmpty
            ? const Center(child: Text('No items yet. Tap + to add one.'))
            : ListView.separated(
                padding: const EdgeInsets.all(16),
                itemCount: itemList.length,
                separatorBuilder: (_, __) => const SizedBox(height: 8),
                itemBuilder: (context, i) => ItemTile(
                  item: itemList[i],
                  onToggle: () => ref.read(itemsProvider.notifier).toggleItem(itemList[i]),
                  onDelete: () => ref.read(itemsProvider.notifier).deleteItem(itemList[i].id),
                ),
              ),
      ),
    );
  }

  void _showAddDialog(BuildContext context, WidgetRef ref) {
    final controller = TextEditingController();
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Add Item'),
        content: TextField(controller: controller, autofocus: true,
          decoration: const InputDecoration(hintText: 'Item title')),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel')),
          FilledButton(
            onPressed: () {
              if (controller.text.trim().isNotEmpty) {
                ref.read(itemsProvider.notifier).addItem(controller.text.trim());
                Navigator.pop(ctx);
              }
            },
            child: const Text('Add'),
          ),
        ],
      ),
    );
  }
}
"""

    def _flutter_item_tile(self) -> str:
        return """import 'package:flutter/material.dart';
import '../models/item.dart';

class ItemTile extends StatelessWidget {
  final Item item;
  final VoidCallback onToggle;
  final VoidCallback onDelete;

  const ItemTile({super.key, required this.item, required this.onToggle, required this.onDelete});

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(color: Colors.grey.shade200),
      ),
      child: ListTile(
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        leading: Checkbox(
          value: item.isCompleted,
          onChanged: (_) => onToggle(),
          activeColor: const Color(0xFF2563EB),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
        ),
        title: Text(
          item.title,
          style: TextStyle(
            decoration: item.isCompleted ? TextDecoration.lineThrough : null,
            color: item.isCompleted ? Colors.grey : Colors.black87,
            fontWeight: FontWeight.w500,
          ),
        ),
        subtitle: item.description != null
            ? Text(item.description!, style: const TextStyle(color: Colors.grey, fontSize: 12))
            : null,
        trailing: IconButton(
          icon: const Icon(Icons.delete_outline, color: Colors.red),
          onPressed: onDelete,
        ),
      ),
    );
  }
}
"""

    def _flutter_login_screen(self) -> str:
        return """import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});
  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _usernameCtrl = TextEditingController();
  final _passwordCtrl = TextEditingController();
  bool _loading = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Sign In', style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.bold)),
              const SizedBox(height: 32),
              TextField(controller: _usernameCtrl, decoration: const InputDecoration(
                labelText: 'Username', border: OutlineInputBorder())),
              const SizedBox(height: 16),
              TextField(controller: _passwordCtrl, obscureText: true, decoration: const InputDecoration(
                labelText: 'Password', border: OutlineInputBorder())),
              const SizedBox(height: 24),
              FilledButton(
                onPressed: _loading ? null : _login,
                style: FilledButton.styleFrom(minimumSize: const Size.fromHeight(48)),
                child: _loading ? const CircularProgressIndicator(color: Colors.white)
                    : const Text('Sign In'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> _login() async {
    setState(() => _loading = true);
    await Future.delayed(const Duration(milliseconds: 500));
    if (mounted) {
      setState(() => _loading = false);
      context.go('/items');
    }
  }
}
"""

    def _flutter_gitignore(self) -> str:
        return """.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.packages
.pub-cache/
.pub/
build/
*.g.dart
*.freezed.dart
"""

    # ── Android Native Generation ─────────────────────────────────────────────

    def _generate_android(self, spec: ArchitectureSpec, out_dir: str) -> list[str]:
        written: list[str] = []
        pkg = f"com.{spec.project_name}"
        written.append(self._write(out_dir, "settings.gradle.kts", f'rootProject.name = "{spec.project_name}"\ninclude(":app")\n'))
        written.append(
            self._write(
                out_dir,
                "build.gradle.kts",
                """plugins {
    id("com.android.application") version "8.2.0" apply false
    id("org.jetbrains.kotlin.android") version "1.9.10" apply false
}
""",
            )
        )
        written.append(self._write(out_dir, "README.md", self._mobile_readme(spec)))
        return written

    # ── Proposed CLI commands (NOT executed) ─────────────────────────────────

    def _get_proposed_commands(self, spec: ArchitectureSpec, mobile_dir: str) -> list[str]:
        if spec.mobile_stack == "Flutter":
            return [
                f"cd {mobile_dir} && flutter pub get",
                f"cd {mobile_dir} && flutter run",
                f"cd {mobile_dir} && flutter build apk --release",
            ]
        return [f"cd {mobile_dir} && ./gradlew assembleDebug"]

    def _mobile_readme(self, spec: ArchitectureSpec) -> str:
        return f"""# {spec.project_name.replace("_", " ").title()} — Mobile ({spec.mobile_stack})

Generated by JARVIS Autonomous SE Platform

## Setup

```bash
cd mobile
flutter pub get       # Install dependencies
flutter run           # Run on connected device/emulator
flutter build apk     # Build release APK
```

## Architecture
- **State Management:** Riverpod
- **Navigation:** GoRouter
- **HTTP Client:** Dio
- **Storage:** shared_preferences + flutter_secure_storage
"""

    def _write(self, directory: str, filename: str, content: str) -> str:
        os.makedirs(directory, exist_ok=True)
        path = os.path.join(directory, filename)
        try:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            return path
        except Exception as e:
            logger.error("MobileAgent write error for %s: %s", path, e)
            return path
