"""
task_manager — FastAPI Application Entry Point
Generated by JARVIS Autonomous Software Engineering Platform
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.database import Base, engine
from app.routes import items


Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Task Manager API",
    description="Auto-generated by JARVIS SE Platform",
    version="1.0.0",
    docs_url="/api/docs",
    redoc_url="/api/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(items.router, prefix="/api/items", tags=["items"])



@app.get("/api/health")
async def health_check():
    return {"status": "online", "service": "task_manager"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
