#!/bin/bash
# task_manager deploy script
# Auto-generated by JARVIS SE Platform

echo "Starting deployment sequence for task_manager..."

# Pull latest code
git pull origin main

# Build and start services using Docker Compose
docker-compose down
docker-compose up --build -d

echo "Deployment complete! Status checks:"
docker-compose ps
