import asyncio
import os
import sys
import ctypes
import tempfile
import time

def get_mci_error_string(code):
    buf = ctypes.create_unicode_buffer(256)
    ctypes.windll.winmm.mciGetErrorStringW(code, buf, 256)
    return buf.value

def test_mci_play(filepath):
    print(f"Testing MCI playback on file: {filepath}")
    if not os.path.exists(filepath):
        print(f"Error: file does not exist: {filepath}")
        return False
        
    size = os.path.getsize(filepath)
    print(f"File size: {size} bytes")
    if size == 0:
        print("Error: audio file is empty")
        return False
        
    buf = ctypes.create_unicode_buffer(260)
    ctypes.windll.kernel32.GetShortPathNameW(filepath, buf, 260)
    short_path = buf.value
    print(f"Short path resolved: '{short_path}'")
    
    # Try stopping/closing
    ret_stop = ctypes.windll.winmm.mciSendStringW("stop jarvis_tts_test", None, 0, 0)
    ret_close = ctypes.windll.winmm.mciSendStringW("close jarvis_tts_test", None, 0, 0)
    print(f"Stop return code: {ret_stop} ({get_mci_error_string(ret_stop)})")
    print(f"Close return code: {ret_close} ({get_mci_error_string(ret_close)})")
    
    # Open
    open_cmd = f"open {short_path} alias jarvis_tts_test"
    print(f"Sending: {open_cmd}")
    ret_open = ctypes.windll.winmm.mciSendStringW(open_cmd, None, 0, 0)
    print(f"Open return code: {ret_open} ({get_mci_error_string(ret_open)})")
    
    if ret_open != 0:
        return False
        
    # Play
    print("Playing (blocking with wait)...")
    t0 = time.time()
    ret_play = ctypes.windll.winmm.mciSendStringW("play jarvis_tts_test wait", None, 0, 0)
    duration = time.time() - t0
    print(f"Play return code: {ret_play} ({get_mci_error_string(ret_play)})")
    print(f"Playback duration: {duration:.2f} seconds")
    
    # Close
    ret_close2 = ctypes.windll.winmm.mciSendStringW("close jarvis_tts_test", None, 0, 0)
    print(f"Final Close return code: {ret_close2} ({get_mci_error_string(ret_close2)})")
    
    return ret_play == 0

async def test_edge_tts_generation():
    print("Testing edge-tts synthesis...")
    try:
        import edge_tts
    except ImportError:
        print("edge-tts is not installed in this environment.")
        return None
        
    text = "Hello, this is a test of the J.A.R.V.I.S. speech synthesis engine."
    voice = "en-GB-RyanNeural"
    communicate = edge_tts.Communicate(text, voice=voice, rate="-8%", pitch="-12Hz")
    audio_data = b""
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            audio_data += chunk["data"]
            
    if not audio_data:
        print("Error: No audio data generated by edge-tts")
        return None
        
    fd, temp_path = tempfile.mkstemp(suffix=".mp3")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(audio_data)
        print(f"Successfully generated temp audio file: {temp_path}")
        return temp_path
    except Exception as e:
        print(f"Failed to write audio file: {e}")
        return None

async def main():
    temp_path = await test_edge_tts_generation()
    if temp_path:
        try:
            success = test_mci_play(temp_path)
            print(f"Overall MCI test success: {success}")
        finally:
            try:
                os.remove(temp_path)
                print("Cleaned up temp audio file.")
            except Exception as e:
                print(f"Failed to clean up: {e}")

if __name__ == "__main__":
    asyncio.run(main())
